### ISSUE TITLE
Use UUIDs to colour staff names

### ISSUE THREAD

**Issue by stupid3700** [stupid3700/StuMCIndex#4]
I blame @pangeacake https://github.com/stupid3700/StuMCIndex/commit/f80680b44f551f634775c3c7832673512e5cfa6f#commitcomment-16109782

**Comment by pangeacake** [comment]
I never even touched that code :/

**Comment by stupid3700** [comment]
Added in 26b75170a1889f5679204dbc05c891b6a03076ca
